[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
guildtrader = { path = "./guildtrader" }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
