/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Assets200Response {
    #[serde(rename = "trades")]
    pub trades: Vec<models::Assets200ResponseTradesInner>,
    #[serde(rename = "last_updated")]
    pub last_updated: String,
}

impl Assets200Response {
    pub fn new(trades: Vec<models::Assets200ResponseTradesInner>, last_updated: String) -> Assets200Response {
        Assets200Response {
            trades,
            last_updated,
        }
    }
}

