/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Assets200ResponseTradesInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "price")]
    pub price: i64,
    #[serde(rename = "price_status")]
    pub price_status: String,
}

impl Assets200ResponseTradesInner {
    pub fn new(name: String, price: i64, price_status: String) -> Assets200ResponseTradesInner {
        Assets200ResponseTradesInner {
            name,
            price,
            price_status,
        }
    }
}

