/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Buy200Response {
    #[serde(rename = "trade")]
    pub trade: Box<models::Trade>,
    #[serde(rename = "gold")]
    pub gold: i64,
}

impl Buy200Response {
    pub fn new(trade: models::Trade, gold: i64) -> Buy200Response {
        Buy200Response {
            trade: Box::new(trade),
            gold,
        }
    }
}

