/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelRequest {
    #[serde(rename = "guild")]
    pub guild: String,
}

impl CancelRequest {
    pub fn new(guild: String) -> CancelRequest {
        CancelRequest {
            guild,
        }
    }
}

