/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contracts200Response {
    #[serde(rename = "data")]
    pub data: Vec<models::Contract>,
    #[serde(rename = "length")]
    pub length: i32,
}

impl Contracts200Response {
    pub fn new(data: Vec<models::Contract>, length: i32) -> Contracts200Response {
        Contracts200Response {
            data,
            length,
        }
    }
}

