/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractRequest {
    #[serde(rename = "guild")]
    pub guild: String,
    #[serde(rename = "item")]
    pub item: String,
    #[serde(rename = "quantity")]
    pub quantity: i64,
}

impl ContractRequest {
    pub fn new(guild: String, item: String, quantity: i64) -> ContractRequest {
        ContractRequest {
            guild,
            item,
            quantity,
        }
    }
}

