/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRequestItemsInner {
    #[serde(rename = "tier")]
    pub tier: i32,
    #[serde(rename = "item")]
    pub item: String,
}

impl GuildRequestItemsInner {
    pub fn new(tier: i32, item: String) -> GuildRequestItemsInner {
        GuildRequestItemsInner {
            tier,
            item,
        }
    }
}

