/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Guild {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "request_items")]
    pub request_items: Vec<models::GuildRequestItemsInner>,
    #[serde(rename = "reward_items")]
    pub reward_items: Vec<models::GuildRewardItemsInner>,
}

impl Guild {
    pub fn new(id: String, name: String, request_items: Vec<models::GuildRequestItemsInner>, reward_items: Vec<models::GuildRewardItemsInner>) -> Guild {
        Guild {
            id,
            name,
            request_items,
            reward_items,
        }
    }
}

