/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRewardItemsInner {
    #[serde(rename = "item")]
    pub item: String,
}

impl GuildRewardItemsInner {
    pub fn new(item: String) -> GuildRewardItemsInner {
        GuildRewardItemsInner {
            item,
        }
    }
}

