/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Leaderboard200ResponseInner {
    #[serde(rename = "rank")]
    pub rank: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "gold")]
    pub gold: i64,
    #[serde(rename = "value")]
    pub value: i64,
}

impl Leaderboard200ResponseInner {
    pub fn new(rank: i64, name: String, gold: i64, value: i64) -> Leaderboard200ResponseInner {
        Leaderboard200ResponseInner {
            rank,
            name,
            gold,
            value,
        }
    }
}

