/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Register201Response {
    #[serde(rename = "user")]
    pub user: Box<models::User>,
    #[serde(rename = "token")]
    pub token: String,
}

impl Register201Response {
    pub fn new(user: models::User, token: String) -> Register201Response {
        Register201Response {
            user: Box::new(user),
            token,
        }
    }
}

