/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterRequest {
    #[serde(rename = "username")]
    pub username: String,
}

impl RegisterRequest {
    pub fn new(username: String) -> RegisterRequest {
        RegisterRequest {
            username,
        }
    }
}

