/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scavenge200Response {
    #[serde(rename = "scavenged")]
    pub scavenged: std::collections::HashMap<String, i64>,
    #[serde(rename = "cooldown")]
    pub cooldown: String,
}

impl Scavenge200Response {
    pub fn new(scavenged: std::collections::HashMap<String, i64>, cooldown: String) -> Scavenge200Response {
        Scavenge200Response {
            scavenged,
            cooldown,
        }
    }
}

