/*
 * guildtrader
 *
 * Guildtrader API
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "gold")]
    pub gold: i64,
    #[serde(rename = "inventory")]
    pub inventory: std::collections::HashMap<String, i64>,
    #[serde(rename = "total_value")]
    pub total_value: i64,
}

impl User {
    pub fn new(username: String, gold: i64, inventory: std::collections::HashMap<String, i64>, total_value: i64) -> User {
        User {
            username,
            gold,
            inventory,
            total_value,
        }
    }
}

